# Rate limiter for demoing pneuma

# Auth Endpoint
map $request_uri $auth_limit_key {
    default "";
    "~^/api/auth" $binary_remote_addr;
}

# Upload Endpoint
map $request_uri $upload_limit_key {
    default "";
    "~^/api/library/tracks/upload" $binary_remote_addr;
}

# General API 
map $request_uri $api_limit_key {
    default "";
    "~^/api(?!/auth|/library/tracks/upload)" $binary_remote_addr;
}

limit_req_zone $auth_limit_key zone=demo_auth:10m rate=10r/s;
limit_req_zone $upload_limit_key zone=demo_upload:10m rate=10r/m;
limit_req_zone $api_limit_key zone=demo_api:10m rate=30r/s;

limit_req_status 429;