services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    networks:
      - proxy-net

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    # networks:
    #   - proxy-net
    environment:
      - "DEFAULT_EMAIL=${LETS_ENCRYPT_EMAIL}"
    depends_on:
      - nginx-proxy

volumes:
  certs:
  html:
  vhost:
  acme:
# networks:
#   proxy-net:
#     name: proxy-net
